#!/bin/bash
dir=`pwd -P`
# if   [ -f is_sos ] || [ -L is_sos ]
# then
#     echo "File exists."
#     #echo  "Please run uninstall.sh first."
#     #exit 1
#     read -p "Do you want to reinstall?[y/n]" isre
#     if  [ $isre == y ]
#     then
#         chmod +x uninstall.sh
#         ./uninstall.sh
#         echo 
#     else
#         exit 1
#     fi
# fi
if [ -f "${HOME}/mosek/mosek.lic" ]
then
    echo -e "\033[32m Mosek license checked. \033[0m"
else
    echo -e "\033[31m Mosek license not found. \033[0m"    
    echo "Pleasa ensure that the license of mosek is valid.(~/mosek/mosek.lic)"
    echo "You can get a free academic license on this website:https://www.mosek.com/products/academic-licenses/"
fi
echo
echo "Which mosek version you want to use"
echo "  1) mosek 8.1"
echo "  2) mosek 9.0"
read -p  "Enter a selection (default=1):" mosek_v
if [ -z $mosek_v ]
then
    mosek_v=1
fi
if ! [ $mosek_v == 1 ] && ! [ $mosek_v == 2 ]
then
    echo -e "\033[31m Invalid Input. \033[0m"
    exit 1
fi

if [ $mosek_v -eq 1 ] && ! [ -d mosek/8 ]
then
    if [ -f mosektoolslinux64x86.tar.bz2 ]
    then
        rm mosektoolslinux64x86.tar.bz2
    fi
    wget https://download.mosek.com/stable/8.1.0.81/mosektoolslinux64x86.tar.bz2
    if [ $? -ne 0 ]
    then
        echo  -e "\033[31m Installation Failed. \033[0m"
        exit 1
    fi
    echo "tar -xjf mosektoolslinux64x86.tar.bz2" 
    tar -xjf mosektoolslinux64x86.tar.bz2
    make -C mosek/8/tools/platform/linux64x86/src/fusion_cxx install
    if [ $? -ne 0 ]
    then
        echo  -e "\033[31m Installation Failed. \033[0m"
        exit 1
    fi
fi
if [ $mosek_v -eq 2 ] && ! [ -d mosek/9.0 ]
then
    if [ -f mosektoolslinux64x86.tar.bz2 ]
    then
        rm mosektoolslinux64x86.tar.bz2
    fi
    wget https://download.mosek.com/stable/9.0.97/mosektoolslinux64x86.tar.bz2
    if [ $? -ne 0 ]
    then
        echo  -e "\033[31m Installation Failed. \033[0m"
        exit 1
    fi
    
    echo "tar -xjf mosektoolslinux64x86.tar.bz2" 
    
    tar -xjf mosektoolslinux64x86.tar.bz2
    make -C mosek/9.0/tools/platform/linux64x86/src/fusion_cxx install
    if [ $? -ne 0 ]
    then
        echo  -e "\033[31m Installation Failed. \033[0m"
        exit 1
    fi
fi
if  ! [ -d lib ]
then
    mkdir lib
fi
if  ! [ -d bin ]
then
    mkdir bin
fi

if [ $mosek_v -eq 1 ] 
then
    cp  -t ./lib/ ./mosek/8/tools/platform/linux64x86/bin/libmosek64.so*  \
        ./mosek/8/tools/platform/linux64x86/bin/libfusion64.a  \
        ./mosek/8/tools/platform/linux64x86/bin/libiomp5.so \
        ./mosek/8/tools/platform/linux64x86/bin/libcilkrts.so.5
else
    cp  -t ./lib/ ./mosek/9.0/tools/platform/linux64x86/bin/libmosek64.so*  \
        ./mosek/9.0/tools/platform/linux64x86/bin/libfusion64.a  \
        ./mosek/9.0/tools/platform/linux64x86/bin/libcilkrts.so.5
fi
if [ $? -ne 0 ]
then
    echo  -e "\033[31m Installation Failed. \033[0m"
    exit 1
fi

if [ $mosek_v -eq 2 ]
then
    make mosek9=1
else
    make  
fi
if [ $? -ne 0 ]
then
    make clean
    echo  -e "\033[31m Installation Failed. \033[0m"
    exit 1
fi

ln -sf ${dir}/bin/is_sos ./
echo  -e "\033[32m Installation Successful. \033[0m"
echo -e "\033[1m Add is_sos to path 
sudo make install \033[0m"
sudo make install
