#!/bin/bash

if [ -f "is_sos" ]
then
    rm is_sos
fi
cd src
make clean
if [ -f "/usr/bin/is_sos" ] 
then 
    echo "If you want to remove is_sos to path, please run:"
    echo "sudo rm /usr/bin/is_sos"
fi